server:
  port: 10005
# spring security 配置
spring:
  security:
    oauth2:
      # 忽略的地址
      ignore-uris: /swagger-ui.html,/swagger-ui/**,/v3/api-docs/**,/doc.html,/webjars/**
# spring doc 配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    info:
      title: 授权demo
      description: 测试swagger授权
      contact:
        name: test
        email: test@qq.com
        url: http://baidu.com/
    packagesToScan: com.msocp.ocpsecurityoauth.controller
  group-configs:
    - group: user
      paths-to-match:
        - /user/**
    - group: login
      paths-to-match:
        - /auth/**
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

authjwt:
  expiration: 600000 # 86400000
  secret:
    key: qwhefiuwhqednqwekdnqkqwerndiwquqcqnckqwnencwqeiuqhdfqwiueduiqwerfddqwedqwdeeqwedqwed
# springdoc 的paths 配置测试
paths:
  /user/add:
    post:
      operationId: addUser
      summary: 123
      description: "[这是一个链接](https://www.baidu.com/)"
